-- table	constraint	type	definition
academic_periods	academic_periods_code_key	unique	UNIQUE (code)
academic_periods	academic_periods_pkey	primary_key	PRIMARY KEY (id)
academic_programs	academic_programs_code_key	unique	UNIQUE (code)
academic_programs	academic_programs_division_id_fkey	foreign_key	FOREIGN KEY (division_id) REFERENCES divisions(id) ON DELETE CASCADE
academic_programs	academic_programs_pkey	primary_key	PRIMARY KEY (id)
activities	activities_academic_period_id_fkey	foreign_key	FOREIGN KEY (academic_period_id) REFERENCES academic_periods(id)
activities	activities_activity_type_code_fkey	foreign_key	FOREIGN KEY (activity_type_code) REFERENCES activity_types(code)
activities	activities_attention_category_code_fkey	foreign_key	FOREIGN KEY (attention_category_code) REFERENCES attention_categories(code)
activities	activities_created_by_fkey	foreign_key	FOREIGN KEY (created_by) REFERENCES auth.users(id)
activities	activities_division_id_fkey	foreign_key	FOREIGN KEY (division_id) REFERENCES divisions(id)
activities	activities_duration_mode_check	check	CHECK (duration_mode IS NULL OR (duration_mode = ANY (ARRAY['one_hour'::text, 'two_hours'::text, 'custom'::text])))
activities	activities_location_type_code_fkey	foreign_key	FOREIGN KEY (location_type_code) REFERENCES location_types(code)
activities	activities_modality_code_fkey	foreign_key	FOREIGN KEY (modality_code) REFERENCES activity_modalities(code)
activities	activities_pkey	primary_key	PRIMARY KEY (id)
activities	activities_program_id_fkey	foreign_key	FOREIGN KEY (program_id) REFERENCES academic_programs(id)
activities	activities_responsible_profile_id_fkey	foreign_key	FOREIGN KEY (responsible_profile_id) REFERENCES profiles(id)
activities	activities_scope_consistency_check	check	CHECK (scope_type = 'program'::text AND program_id IS NOT NULL AND division_id IS NOT NULL OR scope_type = 'division'::text AND division_id IS NOT NULL AND program_id IS NULL)
activities	activities_scope_type_check	check	CHECK (scope_type = ANY (ARRAY['program'::text, 'division'::text]))
activities	activities_service_type_code_fkey	foreign_key	FOREIGN KEY (service_type_code) REFERENCES service_types(code)
activities	activities_status_code_fkey	foreign_key	FOREIGN KEY (status_code) REFERENCES activity_statuses(code)
activities	activities_time_order_check	check	CHECK (starts_at IS NULL OR ends_at IS NULL OR ends_at > starts_at)
activities	activities_updated_by_fkey	foreign_key	FOREIGN KEY (updated_by) REFERENCES auth.users(id)
activity_checkin_tokens	activity_checkin_tokens_activity_id_fkey	foreign_key	FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
activity_checkin_tokens	activity_checkin_tokens_created_by_fkey	foreign_key	FOREIGN KEY (created_by) REFERENCES auth.users(id)
activity_checkin_tokens	activity_checkin_tokens_pkey	primary_key	PRIMARY KEY (id)
activity_checkin_tokens	activity_checkin_tokens_type_check	check	CHECK (token_type = ANY (ARRAY['attendance'::text, 'registration'::text]))
activity_modalities	activity_modalities_pkey	primary_key	PRIMARY KEY (code)
activity_participants	activity_participants_activity_id_fkey	foreign_key	FOREIGN KEY (activity_id) REFERENCES activities(id) ON DELETE CASCADE
activity_participants	activity_participants_added_by_fkey	foreign_key	FOREIGN KEY (added_by) REFERENCES auth.users(id)
activity_participants	activity_participants_attendance_source_check	check	CHECK (attendance_source = ANY (ARRAY['system'::text, 'manual'::text, 'qr'::text, 'code'::text]))
activity_participants	activity_participants_attendance_status_check	check	CHECK (attendance_status = ANY (ARRAY['pending'::text, 'attended'::text, 'absent'::text, 'justified'::text]))
activity_participants	activity_participants_attendance_updated_by_fkey	foreign_key	FOREIGN KEY (attendance_updated_by) REFERENCES auth.users(id)
activity_participants	activity_participants_participant_role_code_fkey	foreign_key	FOREIGN KEY (participant_role_code) REFERENCES participant_roles(code)
activity_participants	activity_participants_pkey	primary_key	PRIMARY KEY (id)
activity_participants	activity_participants_profile_id_fkey	foreign_key	FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE RESTRICT
activity_participants	activity_participants_unique_profile_per_activity	unique	UNIQUE (activity_id, profile_id)
activity_statuses	activity_statuses_pkey	primary_key	PRIMARY KEY (code)
activity_types	activity_types_pkey	primary_key	PRIMARY KEY (code)
attention_categories	attention_categories_pkey	primary_key	PRIMARY KEY (code)
divisions	divisions_code_key	unique	UNIQUE (code)
divisions	divisions_pkey	primary_key	PRIMARY KEY (id)
location_types	location_types_pkey	primary_key	PRIMARY KEY (code)
participant_roles	participant_roles_pkey	primary_key	PRIMARY KEY (code)
profiles	profiles_id_fkey	foreign_key	FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
profiles	profiles_institutional_id_type_check	check	CHECK (institutional_id_type IS NULL OR (institutional_id_type = ANY (ARRAY['student_account'::text, 'worker_number'::text])))
profiles	profiles_person_identifier_consistency_check	check	CHECK (person_type IS NULL OR institutional_id_type IS NULL OR person_type = 'student'::text AND institutional_id_type = 'student_account'::text OR person_type = 'worker'::text AND institutional_id_type = 'worker_number'::text)
profiles	profiles_person_type_check	check	CHECK (person_type IS NULL OR (person_type = ANY (ARRAY['student'::text, 'worker'::text])))
profiles	profiles_pkey	primary_key	PRIMARY KEY (id)
profiles	profiles_primary_program_id_fkey	foreign_key	FOREIGN KEY (primary_program_id) REFERENCES academic_programs(id)
role_assignments	role_assignments_assigned_by_fkey	foreign_key	FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
role_assignments	role_assignments_division_id_fkey	foreign_key	FOREIGN KEY (division_id) REFERENCES divisions(id) ON DELETE CASCADE
role_assignments	role_assignments_pkey	primary_key	PRIMARY KEY (id)
role_assignments	role_assignments_program_id_fkey	foreign_key	FOREIGN KEY (program_id) REFERENCES academic_programs(id) ON DELETE CASCADE
role_assignments	role_assignments_role_code_fkey	foreign_key	FOREIGN KEY (role_code) REFERENCES roles(code)
role_assignments	role_assignments_scope_type_check	check	CHECK (scope_type = ANY (ARRAY['own'::text, 'program'::text, 'division'::text, 'system'::text]))
role_assignments	role_assignments_service_area_check	check	CHECK (service_area = ANY (ARRAY['tutoring'::text, 'advising'::text, 'both'::text, 'logistics'::text, 'technical'::text]))
role_assignments	role_assignments_user_id_fkey	foreign_key	FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
role_assignments	valid_role_assignment_scope	check	CHECK (scope_type = 'own'::text AND division_id IS NULL AND program_id IS NULL OR scope_type = 'program'::text AND program_id IS NOT NULL OR scope_type = 'division'::text AND division_id IS NOT NULL OR scope_type = 'system'::text AND division_id IS NULL AND program_id IS NULL)
roles	roles_pkey	primary_key	PRIMARY KEY (code)
service_types	service_types_pkey	primary_key	PRIMARY KEY (code)
system_health	system_health_pkey	primary_key	PRIMARY KEY (id)
