-- object_type	object_identity	owner	grantor	grantee	privilege_type	is_grantable	raw_acl
function	activity_attendance_deadline(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_attendance_deadline(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_attendance_deadline(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_attendance_open_at(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_attendance_open_at(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_attendance_open_at(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_has_ended(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_has_ended(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	activity_has_ended(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	add_activity_participant(uuid,uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	add_activity_participant(uuid,uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	add_activity_participant(uuid,uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(text,uuid,uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(text,uuid,uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(text,uuid,uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_create_activity(uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_delete_activity(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_delete_activity(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_delete_activity(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_edit_activity(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_edit_activity(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_edit_activity(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(text,uuid,uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(text,uuid,uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(text,uuid,uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_manage_activity(uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_read_activity(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_read_activity(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_read_activity(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_update_activity_base(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_update_activity_base(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	can_update_activity_base(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	check_in_activity(text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	check_in_activity(text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	check_in_activity(text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	close_activity_attendance_checkin(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	close_activity_attendance_checkin(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	close_activity_attendance_checkin(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	complete_own_google_registration(text,text,text,text,text,uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,service_role=X/postgres,authenticated=X/postgres
function	complete_own_google_registration(text,text,text,text,text,uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres,authenticated=X/postgres
function	complete_own_google_registration(text,text,text,text,text,uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres,authenticated=X/postgres
function	complete_own_google_registration(text,text,text,uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	complete_own_google_registration(text,text,text,uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	enforce_sitaa_profile_identity()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	enforce_sitaa_profile_identity()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	finalize_expired_attendance()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	finalize_expired_attendance()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	finalize_expired_attendance()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	generate_three_word_code()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	generate_three_word_code()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	generate_three_word_code()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_academic_period_for_date(date)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_academic_period_for_date(date)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_academic_period_for_date(date)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_active_activity_attendance_checkin(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_active_activity_attendance_checkin(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_active_activity_attendance_checkin(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_attendance_checkin_state(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_attendance_checkin_state(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_attendance_checkin_state(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_participants(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_participants(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_activity_participants(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_visible_activity_cards()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_visible_activity_cards()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	get_visible_activity_cards()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	guard_activity_participant_pending_deadline()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	guard_activity_participant_pending_deadline()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	guard_activity_participant_pending_deadline()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	handle_sitaa_auth_user_created()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	handle_sitaa_auth_user_created()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	has_active_role(text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	has_active_role(text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	has_active_role(text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	has_any_active_role(text[])	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	has_any_active_role(text[])	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	has_any_active_role(text[])	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	is_activity_participant(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	is_activity_participant(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	is_activity_participant(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	normalize_sitaa_profile_names()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	normalize_sitaa_profile_names()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	open_activity_attendance_checkin(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	open_activity_attendance_checkin(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	open_activity_attendance_checkin(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	publish_activity(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	publish_activity(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	publish_activity(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	remove_activity_participant(uuid)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	remove_activity_participant(uuid)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	remove_activity_participant(uuid)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	search_profiles_for_participation(uuid,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	search_profiles_for_participation(uuid,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	search_profiles_for_participation(uuid,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	set_updated_at()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	set_updated_at()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	set_updated_at()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	sync_sitaa_profile_email_from_auth()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	sync_sitaa_profile_email_from_auth()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,service_role=X/postgres
function	update_activity_participant_attendance(uuid,text,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	update_activity_participant_attendance(uuid,text,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	update_activity_participant_attendance(uuid,text,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	update_activity_participants_attendance_bulk(uuid,uuid[],text,text)	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	update_activity_participants_attendance_bulk(uuid,uuid[],text,text)	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	update_activity_participants_attendance_bulk(uuid,uuid[],text,text)	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	validate_activity_scheduled_state()	postgres	postgres	authenticated	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	validate_activity_scheduled_state()	postgres	postgres	postgres	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
function	validate_activity_scheduled_state()	postgres	postgres	service_role	EXECUTE	false	postgres=X/postgres,authenticated=X/postgres,service_role=X/postgres
sequence	system_health_id_seq	postgres	postgres	postgres	SELECT	false	postgres=rwU/postgres,service_role=rwU/postgres
sequence	system_health_id_seq	postgres	postgres	postgres	UPDATE	false	postgres=rwU/postgres,service_role=rwU/postgres
sequence	system_health_id_seq	postgres	postgres	postgres	USAGE	false	postgres=rwU/postgres,service_role=rwU/postgres
sequence	system_health_id_seq	postgres	postgres	service_role	SELECT	false	postgres=rwU/postgres,service_role=rwU/postgres
sequence	system_health_id_seq	postgres	postgres	service_role	UPDATE	false	postgres=rwU/postgres,service_role=rwU/postgres
sequence	system_health_id_seq	postgres	postgres	service_role	USAGE	false	postgres=rwU/postgres,service_role=rwU/postgres
table	academic_periods	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_periods	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	academic_programs	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activities	postgres	postgres	authenticated	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	authenticated	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	authenticated	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activities	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_checkin_tokens	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres
table	activity_modalities	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_modalities	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_participants	postgres	postgres	authenticated	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	authenticated	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	authenticated	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_participants	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=arwd/postgres
table	activity_statuses	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_statuses	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	activity_types	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	attention_categories	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	divisions	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	location_types	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	participant_roles	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	profiles	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	role_assignments	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	roles	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	service_types	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	anon	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	authenticated	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	postgres	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	DELETE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	INSERT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	MAINTAIN	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	REFERENCES	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	SELECT	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	TRIGGER	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	TRUNCATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
table	system_health	postgres	postgres	service_role	UPDATE	false	postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,anon=r/postgres,authenticated=r/postgres
