-- table_schema	table_name	grantor	grantee	privilege_type	is_grantable	with_hierarchy
public	academic_periods	postgres	authenticated	SELECT	NO	YES
public	academic_periods	postgres	postgres	DELETE	YES	NO
public	academic_periods	postgres	postgres	INSERT	YES	NO
public	academic_periods	postgres	postgres	REFERENCES	YES	NO
public	academic_periods	postgres	postgres	SELECT	YES	YES
public	academic_periods	postgres	postgres	TRIGGER	YES	NO
public	academic_periods	postgres	postgres	TRUNCATE	YES	NO
public	academic_periods	postgres	postgres	UPDATE	YES	NO
public	academic_periods	postgres	service_role	DELETE	NO	NO
public	academic_periods	postgres	service_role	INSERT	NO	NO
public	academic_periods	postgres	service_role	REFERENCES	NO	NO
public	academic_periods	postgres	service_role	SELECT	NO	YES
public	academic_periods	postgres	service_role	TRIGGER	NO	NO
public	academic_periods	postgres	service_role	TRUNCATE	NO	NO
public	academic_periods	postgres	service_role	UPDATE	NO	NO
public	academic_programs	postgres	authenticated	SELECT	NO	YES
public	academic_programs	postgres	postgres	DELETE	YES	NO
public	academic_programs	postgres	postgres	INSERT	YES	NO
public	academic_programs	postgres	postgres	REFERENCES	YES	NO
public	academic_programs	postgres	postgres	SELECT	YES	YES
public	academic_programs	postgres	postgres	TRIGGER	YES	NO
public	academic_programs	postgres	postgres	TRUNCATE	YES	NO
public	academic_programs	postgres	postgres	UPDATE	YES	NO
public	academic_programs	postgres	service_role	DELETE	NO	NO
public	academic_programs	postgres	service_role	INSERT	NO	NO
public	academic_programs	postgres	service_role	REFERENCES	NO	NO
public	academic_programs	postgres	service_role	SELECT	NO	YES
public	academic_programs	postgres	service_role	TRIGGER	NO	NO
public	academic_programs	postgres	service_role	TRUNCATE	NO	NO
public	academic_programs	postgres	service_role	UPDATE	NO	NO
public	activities	postgres	authenticated	DELETE	NO	NO
public	activities	postgres	authenticated	INSERT	NO	NO
public	activities	postgres	authenticated	SELECT	NO	YES
public	activities	postgres	authenticated	UPDATE	NO	NO
public	activities	postgres	postgres	DELETE	YES	NO
public	activities	postgres	postgres	INSERT	YES	NO
public	activities	postgres	postgres	REFERENCES	YES	NO
public	activities	postgres	postgres	SELECT	YES	YES
public	activities	postgres	postgres	TRIGGER	YES	NO
public	activities	postgres	postgres	TRUNCATE	YES	NO
public	activities	postgres	postgres	UPDATE	YES	NO
public	activities	postgres	service_role	DELETE	NO	NO
public	activities	postgres	service_role	INSERT	NO	NO
public	activities	postgres	service_role	REFERENCES	NO	NO
public	activities	postgres	service_role	SELECT	NO	YES
public	activities	postgres	service_role	TRIGGER	NO	NO
public	activities	postgres	service_role	TRUNCATE	NO	NO
public	activities	postgres	service_role	UPDATE	NO	NO
public	activity_checkin_tokens	postgres	postgres	DELETE	YES	NO
public	activity_checkin_tokens	postgres	postgres	INSERT	YES	NO
public	activity_checkin_tokens	postgres	postgres	REFERENCES	YES	NO
public	activity_checkin_tokens	postgres	postgres	SELECT	YES	YES
public	activity_checkin_tokens	postgres	postgres	TRIGGER	YES	NO
public	activity_checkin_tokens	postgres	postgres	TRUNCATE	YES	NO
public	activity_checkin_tokens	postgres	postgres	UPDATE	YES	NO
public	activity_checkin_tokens	postgres	service_role	DELETE	NO	NO
public	activity_checkin_tokens	postgres	service_role	INSERT	NO	NO
public	activity_checkin_tokens	postgres	service_role	REFERENCES	NO	NO
public	activity_checkin_tokens	postgres	service_role	SELECT	NO	YES
public	activity_checkin_tokens	postgres	service_role	TRIGGER	NO	NO
public	activity_checkin_tokens	postgres	service_role	TRUNCATE	NO	NO
public	activity_checkin_tokens	postgres	service_role	UPDATE	NO	NO
public	activity_modalities	postgres	authenticated	SELECT	NO	YES
public	activity_modalities	postgres	postgres	DELETE	YES	NO
public	activity_modalities	postgres	postgres	INSERT	YES	NO
public	activity_modalities	postgres	postgres	REFERENCES	YES	NO
public	activity_modalities	postgres	postgres	SELECT	YES	YES
public	activity_modalities	postgres	postgres	TRIGGER	YES	NO
public	activity_modalities	postgres	postgres	TRUNCATE	YES	NO
public	activity_modalities	postgres	postgres	UPDATE	YES	NO
public	activity_modalities	postgres	service_role	DELETE	NO	NO
public	activity_modalities	postgres	service_role	INSERT	NO	NO
public	activity_modalities	postgres	service_role	REFERENCES	NO	NO
public	activity_modalities	postgres	service_role	SELECT	NO	YES
public	activity_modalities	postgres	service_role	TRIGGER	NO	NO
public	activity_modalities	postgres	service_role	TRUNCATE	NO	NO
public	activity_modalities	postgres	service_role	UPDATE	NO	NO
public	activity_participants	postgres	authenticated	DELETE	NO	NO
public	activity_participants	postgres	authenticated	INSERT	NO	NO
public	activity_participants	postgres	authenticated	SELECT	NO	YES
public	activity_participants	postgres	authenticated	UPDATE	NO	NO
public	activity_participants	postgres	postgres	DELETE	YES	NO
public	activity_participants	postgres	postgres	INSERT	YES	NO
public	activity_participants	postgres	postgres	REFERENCES	YES	NO
public	activity_participants	postgres	postgres	SELECT	YES	YES
public	activity_participants	postgres	postgres	TRIGGER	YES	NO
public	activity_participants	postgres	postgres	TRUNCATE	YES	NO
public	activity_participants	postgres	postgres	UPDATE	YES	NO
public	activity_participants	postgres	service_role	DELETE	NO	NO
public	activity_participants	postgres	service_role	INSERT	NO	NO
public	activity_participants	postgres	service_role	REFERENCES	NO	NO
public	activity_participants	postgres	service_role	SELECT	NO	YES
public	activity_participants	postgres	service_role	TRIGGER	NO	NO
public	activity_participants	postgres	service_role	TRUNCATE	NO	NO
public	activity_participants	postgres	service_role	UPDATE	NO	NO
public	activity_statuses	postgres	authenticated	SELECT	NO	YES
public	activity_statuses	postgres	postgres	DELETE	YES	NO
public	activity_statuses	postgres	postgres	INSERT	YES	NO
public	activity_statuses	postgres	postgres	REFERENCES	YES	NO
public	activity_statuses	postgres	postgres	SELECT	YES	YES
public	activity_statuses	postgres	postgres	TRIGGER	YES	NO
public	activity_statuses	postgres	postgres	TRUNCATE	YES	NO
public	activity_statuses	postgres	postgres	UPDATE	YES	NO
public	activity_statuses	postgres	service_role	DELETE	NO	NO
public	activity_statuses	postgres	service_role	INSERT	NO	NO
public	activity_statuses	postgres	service_role	REFERENCES	NO	NO
public	activity_statuses	postgres	service_role	SELECT	NO	YES
public	activity_statuses	postgres	service_role	TRIGGER	NO	NO
public	activity_statuses	postgres	service_role	TRUNCATE	NO	NO
public	activity_statuses	postgres	service_role	UPDATE	NO	NO
public	activity_types	postgres	authenticated	SELECT	NO	YES
public	activity_types	postgres	postgres	DELETE	YES	NO
public	activity_types	postgres	postgres	INSERT	YES	NO
public	activity_types	postgres	postgres	REFERENCES	YES	NO
public	activity_types	postgres	postgres	SELECT	YES	YES
public	activity_types	postgres	postgres	TRIGGER	YES	NO
public	activity_types	postgres	postgres	TRUNCATE	YES	NO
public	activity_types	postgres	postgres	UPDATE	YES	NO
public	activity_types	postgres	service_role	DELETE	NO	NO
public	activity_types	postgres	service_role	INSERT	NO	NO
public	activity_types	postgres	service_role	REFERENCES	NO	NO
public	activity_types	postgres	service_role	SELECT	NO	YES
public	activity_types	postgres	service_role	TRIGGER	NO	NO
public	activity_types	postgres	service_role	TRUNCATE	NO	NO
public	activity_types	postgres	service_role	UPDATE	NO	NO
public	admin_audit_events	postgres	postgres	DELETE	YES	NO
public	admin_audit_events	postgres	postgres	INSERT	YES	NO
public	admin_audit_events	postgres	postgres	REFERENCES	YES	NO
public	admin_audit_events	postgres	postgres	SELECT	YES	YES
public	admin_audit_events	postgres	postgres	TRIGGER	YES	NO
public	admin_audit_events	postgres	postgres	TRUNCATE	YES	NO
public	admin_audit_events	postgres	postgres	UPDATE	YES	NO
public	admin_audit_events	postgres	service_role	INSERT	NO	NO
public	admin_audit_events	postgres	service_role	SELECT	NO	YES
public	attention_categories	postgres	authenticated	SELECT	NO	YES
public	attention_categories	postgres	postgres	DELETE	YES	NO
public	attention_categories	postgres	postgres	INSERT	YES	NO
public	attention_categories	postgres	postgres	REFERENCES	YES	NO
public	attention_categories	postgres	postgres	SELECT	YES	YES
public	attention_categories	postgres	postgres	TRIGGER	YES	NO
public	attention_categories	postgres	postgres	TRUNCATE	YES	NO
public	attention_categories	postgres	postgres	UPDATE	YES	NO
public	attention_categories	postgres	service_role	DELETE	NO	NO
public	attention_categories	postgres	service_role	INSERT	NO	NO
public	attention_categories	postgres	service_role	REFERENCES	NO	NO
public	attention_categories	postgres	service_role	SELECT	NO	YES
public	attention_categories	postgres	service_role	TRIGGER	NO	NO
public	attention_categories	postgres	service_role	TRUNCATE	NO	NO
public	attention_categories	postgres	service_role	UPDATE	NO	NO
public	divisions	postgres	authenticated	SELECT	NO	YES
public	divisions	postgres	postgres	DELETE	YES	NO
public	divisions	postgres	postgres	INSERT	YES	NO
public	divisions	postgres	postgres	REFERENCES	YES	NO
public	divisions	postgres	postgres	SELECT	YES	YES
public	divisions	postgres	postgres	TRIGGER	YES	NO
public	divisions	postgres	postgres	TRUNCATE	YES	NO
public	divisions	postgres	postgres	UPDATE	YES	NO
public	divisions	postgres	service_role	DELETE	NO	NO
public	divisions	postgres	service_role	INSERT	NO	NO
public	divisions	postgres	service_role	REFERENCES	NO	NO
public	divisions	postgres	service_role	SELECT	NO	YES
public	divisions	postgres	service_role	TRIGGER	NO	NO
public	divisions	postgres	service_role	TRUNCATE	NO	NO
public	divisions	postgres	service_role	UPDATE	NO	NO
public	location_types	postgres	authenticated	SELECT	NO	YES
public	location_types	postgres	postgres	DELETE	YES	NO
public	location_types	postgres	postgres	INSERT	YES	NO
public	location_types	postgres	postgres	REFERENCES	YES	NO
public	location_types	postgres	postgres	SELECT	YES	YES
public	location_types	postgres	postgres	TRIGGER	YES	NO
public	location_types	postgres	postgres	TRUNCATE	YES	NO
public	location_types	postgres	postgres	UPDATE	YES	NO
public	location_types	postgres	service_role	DELETE	NO	NO
public	location_types	postgres	service_role	INSERT	NO	NO
public	location_types	postgres	service_role	REFERENCES	NO	NO
public	location_types	postgres	service_role	SELECT	NO	YES
public	location_types	postgres	service_role	TRIGGER	NO	NO
public	location_types	postgres	service_role	TRUNCATE	NO	NO
public	location_types	postgres	service_role	UPDATE	NO	NO
public	participant_roles	postgres	authenticated	SELECT	NO	YES
public	participant_roles	postgres	postgres	DELETE	YES	NO
public	participant_roles	postgres	postgres	INSERT	YES	NO
public	participant_roles	postgres	postgres	REFERENCES	YES	NO
public	participant_roles	postgres	postgres	SELECT	YES	YES
public	participant_roles	postgres	postgres	TRIGGER	YES	NO
public	participant_roles	postgres	postgres	TRUNCATE	YES	NO
public	participant_roles	postgres	postgres	UPDATE	YES	NO
public	participant_roles	postgres	service_role	DELETE	NO	NO
public	participant_roles	postgres	service_role	INSERT	NO	NO
public	participant_roles	postgres	service_role	REFERENCES	NO	NO
public	participant_roles	postgres	service_role	SELECT	NO	YES
public	participant_roles	postgres	service_role	TRIGGER	NO	NO
public	participant_roles	postgres	service_role	TRUNCATE	NO	NO
public	participant_roles	postgres	service_role	UPDATE	NO	NO
public	profiles	postgres	authenticated	SELECT	NO	YES
public	profiles	postgres	postgres	DELETE	YES	NO
public	profiles	postgres	postgres	INSERT	YES	NO
public	profiles	postgres	postgres	REFERENCES	YES	NO
public	profiles	postgres	postgres	SELECT	YES	YES
public	profiles	postgres	postgres	TRIGGER	YES	NO
public	profiles	postgres	postgres	TRUNCATE	YES	NO
public	profiles	postgres	postgres	UPDATE	YES	NO
public	profiles	postgres	service_role	DELETE	NO	NO
public	profiles	postgres	service_role	INSERT	NO	NO
public	profiles	postgres	service_role	REFERENCES	NO	NO
public	profiles	postgres	service_role	SELECT	NO	YES
public	profiles	postgres	service_role	TRIGGER	NO	NO
public	profiles	postgres	service_role	TRUNCATE	NO	NO
public	profiles	postgres	service_role	UPDATE	NO	NO
public	role_assignments	postgres	authenticated	SELECT	NO	YES
public	role_assignments	postgres	postgres	DELETE	YES	NO
public	role_assignments	postgres	postgres	INSERT	YES	NO
public	role_assignments	postgres	postgres	REFERENCES	YES	NO
public	role_assignments	postgres	postgres	SELECT	YES	YES
public	role_assignments	postgres	postgres	TRIGGER	YES	NO
public	role_assignments	postgres	postgres	TRUNCATE	YES	NO
public	role_assignments	postgres	postgres	UPDATE	YES	NO
public	role_assignments	postgres	service_role	DELETE	NO	NO
public	role_assignments	postgres	service_role	INSERT	NO	NO
public	role_assignments	postgres	service_role	REFERENCES	NO	NO
public	role_assignments	postgres	service_role	SELECT	NO	YES
public	role_assignments	postgres	service_role	TRIGGER	NO	NO
public	role_assignments	postgres	service_role	TRUNCATE	NO	NO
public	role_assignments	postgres	service_role	UPDATE	NO	NO
public	roles	postgres	authenticated	SELECT	NO	YES
public	roles	postgres	postgres	DELETE	YES	NO
public	roles	postgres	postgres	INSERT	YES	NO
public	roles	postgres	postgres	REFERENCES	YES	NO
public	roles	postgres	postgres	SELECT	YES	YES
public	roles	postgres	postgres	TRIGGER	YES	NO
public	roles	postgres	postgres	TRUNCATE	YES	NO
public	roles	postgres	postgres	UPDATE	YES	NO
public	roles	postgres	service_role	DELETE	NO	NO
public	roles	postgres	service_role	INSERT	NO	NO
public	roles	postgres	service_role	REFERENCES	NO	NO
public	roles	postgres	service_role	SELECT	NO	YES
public	roles	postgres	service_role	TRIGGER	NO	NO
public	roles	postgres	service_role	TRUNCATE	NO	NO
public	roles	postgres	service_role	UPDATE	NO	NO
public	service_types	postgres	authenticated	SELECT	NO	YES
public	service_types	postgres	postgres	DELETE	YES	NO
public	service_types	postgres	postgres	INSERT	YES	NO
public	service_types	postgres	postgres	REFERENCES	YES	NO
public	service_types	postgres	postgres	SELECT	YES	YES
public	service_types	postgres	postgres	TRIGGER	YES	NO
public	service_types	postgres	postgres	TRUNCATE	YES	NO
public	service_types	postgres	postgres	UPDATE	YES	NO
public	service_types	postgres	service_role	DELETE	NO	NO
public	service_types	postgres	service_role	INSERT	NO	NO
public	service_types	postgres	service_role	REFERENCES	NO	NO
public	service_types	postgres	service_role	SELECT	NO	YES
public	service_types	postgres	service_role	TRIGGER	NO	NO
public	service_types	postgres	service_role	TRUNCATE	NO	NO
public	service_types	postgres	service_role	UPDATE	NO	NO
public	system_health	postgres	anon	SELECT	NO	YES
public	system_health	postgres	authenticated	SELECT	NO	YES
public	system_health	postgres	postgres	DELETE	YES	NO
public	system_health	postgres	postgres	INSERT	YES	NO
public	system_health	postgres	postgres	REFERENCES	YES	NO
public	system_health	postgres	postgres	SELECT	YES	YES
public	system_health	postgres	postgres	TRIGGER	YES	NO
public	system_health	postgres	postgres	TRUNCATE	YES	NO
public	system_health	postgres	postgres	UPDATE	YES	NO
public	system_health	postgres	service_role	DELETE	NO	NO
public	system_health	postgres	service_role	INSERT	NO	NO
public	system_health	postgres	service_role	REFERENCES	NO	NO
public	system_health	postgres	service_role	SELECT	NO	YES
public	system_health	postgres	service_role	TRIGGER	NO	NO
public	system_health	postgres	service_role	TRUNCATE	NO	NO
public	system_health	postgres	service_role	UPDATE	NO	NO
