-- schema	table	index	definition
public	academic_periods	academic_periods_code_key	CREATE UNIQUE INDEX academic_periods_code_key ON public.academic_periods USING btree (code)
public	academic_periods	academic_periods_pkey	CREATE UNIQUE INDEX academic_periods_pkey ON public.academic_periods USING btree (id)
public	academic_programs	academic_programs_code_key	CREATE UNIQUE INDEX academic_programs_code_key ON public.academic_programs USING btree (code)
public	academic_programs	academic_programs_pkey	CREATE UNIQUE INDEX academic_programs_pkey ON public.academic_programs USING btree (id)
public	activities	activities_created_by_idx	CREATE INDEX activities_created_by_idx ON public.activities USING btree (created_by)
public	activities	activities_division_id_idx	CREATE INDEX activities_division_id_idx ON public.activities USING btree (division_id)
public	activities	activities_pkey	CREATE UNIQUE INDEX activities_pkey ON public.activities USING btree (id)
public	activities	activities_program_id_idx	CREATE INDEX activities_program_id_idx ON public.activities USING btree (program_id)
public	activities	activities_responsible_profile_id_idx	CREATE INDEX activities_responsible_profile_id_idx ON public.activities USING btree (responsible_profile_id)
public	activities	activities_scope_type_idx	CREATE INDEX activities_scope_type_idx ON public.activities USING btree (scope_type)
public	activities	activities_service_type_code_idx	CREATE INDEX activities_service_type_code_idx ON public.activities USING btree (service_type_code)
public	activities	activities_starts_at_idx	CREATE INDEX activities_starts_at_idx ON public.activities USING btree (starts_at)
public	activities	activities_status_code_idx	CREATE INDEX activities_status_code_idx ON public.activities USING btree (status_code)
public	activity_checkin_tokens	activity_checkin_tokens_active_code_words_idx	CREATE UNIQUE INDEX activity_checkin_tokens_active_code_words_idx ON public.activity_checkin_tokens USING btree (code_words) WHERE (is_active = true)
public	activity_checkin_tokens	activity_checkin_tokens_activity_id_idx	CREATE INDEX activity_checkin_tokens_activity_id_idx ON public.activity_checkin_tokens USING btree (activity_id)
public	activity_checkin_tokens	activity_checkin_tokens_one_active_attendance_idx	CREATE UNIQUE INDEX activity_checkin_tokens_one_active_attendance_idx ON public.activity_checkin_tokens USING btree (activity_id, token_type) WHERE ((is_active = true) AND (token_type = 'attendance'::text))
public	activity_checkin_tokens	activity_checkin_tokens_pkey	CREATE UNIQUE INDEX activity_checkin_tokens_pkey ON public.activity_checkin_tokens USING btree (id)
public	activity_checkin_tokens	activity_checkin_tokens_secret_token_idx	CREATE UNIQUE INDEX activity_checkin_tokens_secret_token_idx ON public.activity_checkin_tokens USING btree (secret_token)
public	activity_modalities	activity_modalities_pkey	CREATE UNIQUE INDEX activity_modalities_pkey ON public.activity_modalities USING btree (code)
public	activity_participants	activity_participants_activity_id_idx	CREATE INDEX activity_participants_activity_id_idx ON public.activity_participants USING btree (activity_id)
public	activity_participants	activity_participants_attendance_status_idx	CREATE INDEX activity_participants_attendance_status_idx ON public.activity_participants USING btree (attendance_status)
public	activity_participants	activity_participants_pkey	CREATE UNIQUE INDEX activity_participants_pkey ON public.activity_participants USING btree (id)
public	activity_participants	activity_participants_profile_id_idx	CREATE INDEX activity_participants_profile_id_idx ON public.activity_participants USING btree (profile_id)
public	activity_participants	activity_participants_role_idx	CREATE INDEX activity_participants_role_idx ON public.activity_participants USING btree (participant_role_code)
public	activity_participants	activity_participants_unique_profile_per_activity	CREATE UNIQUE INDEX activity_participants_unique_profile_per_activity ON public.activity_participants USING btree (activity_id, profile_id)
public	activity_statuses	activity_statuses_pkey	CREATE UNIQUE INDEX activity_statuses_pkey ON public.activity_statuses USING btree (code)
public	activity_types	activity_types_pkey	CREATE UNIQUE INDEX activity_types_pkey ON public.activity_types USING btree (code)
public	admin_audit_events	admin_audit_events_actor_occurred_idx	CREATE INDEX admin_audit_events_actor_occurred_idx ON public.admin_audit_events USING btree (actor_profile_id, occurred_at DESC, id DESC)
public	admin_audit_events	admin_audit_events_pkey	CREATE UNIQUE INDEX admin_audit_events_pkey ON public.admin_audit_events USING btree (id)
public	admin_audit_events	admin_audit_events_target_occurred_idx	CREATE INDEX admin_audit_events_target_occurred_idx ON public.admin_audit_events USING btree (target_profile_id, occurred_at DESC, id DESC)
public	attention_categories	attention_categories_pkey	CREATE UNIQUE INDEX attention_categories_pkey ON public.attention_categories USING btree (code)
public	divisions	divisions_code_key	CREATE UNIQUE INDEX divisions_code_key ON public.divisions USING btree (code)
public	divisions	divisions_pkey	CREATE UNIQUE INDEX divisions_pkey ON public.divisions USING btree (id)
public	location_types	location_types_pkey	CREATE UNIQUE INDEX location_types_pkey ON public.location_types USING btree (code)
public	participant_roles	participant_roles_pkey	CREATE UNIQUE INDEX participant_roles_pkey ON public.participant_roles USING btree (code)
public	profiles	profiles_admin_directory_filters_idx	CREATE INDEX profiles_admin_directory_filters_idx ON public.profiles USING btree (account_status, account_kind, person_type, primary_program_id)
public	profiles	profiles_admin_directory_sort_idx	CREATE INDEX profiles_admin_directory_sort_idx ON public.profiles USING btree (paternal_surname, maternal_surname, first_names, id)
public	profiles	profiles_institutional_identifier_pair_key	CREATE UNIQUE INDEX profiles_institutional_identifier_pair_key ON public.profiles USING btree (institutional_id_type, institutional_id_value) WHERE ((account_kind = 'institutional'::text) AND (institutional_id_value IS NOT NULL))
public	profiles	profiles_pkey	CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id)
public	role_assignments	role_assignments_pkey	CREATE UNIQUE INDEX role_assignments_pkey ON public.role_assignments USING btree (id)
public	roles	roles_pkey	CREATE UNIQUE INDEX roles_pkey ON public.roles USING btree (code)
public	service_types	service_types_pkey	CREATE UNIQUE INDEX service_types_pkey ON public.service_types USING btree (code)
public	system_health	system_health_pkey	CREATE UNIQUE INDEX system_health_pkey ON public.system_health USING btree (id)
